### ISSUE TITLE
Some embedded media links are not detected {liens de média non détectés}

### ISSUE THREAD

**Issue by kekukui** [regseb/castkodi#11]
CastKodi fails to recognize embedded MP3, MP4, M3U links which are clearly visible in the page source.  These media links could be detected automatically, and should not require a site-specific script.
_____
CastKodi ne reconnaît pas les liens MP3, MP4, M3U incorporés qui sont clairement visibles dans le page source code. Ces liens multimédia pourraient être détectés automatiquement et ne devraient pas nécessiter de script spécifique au site.

**Comment by regseb** [comment]
@kekukui Cast Kodi searches music and videos in the HTML tags `<audio>` and `<video>`. Do you have an example of a page where links are not found?

**Comment by regseb** [comment]
@kekukui With the new version _4.3.0_, you can send the media from [_Blog Talk Radio_](https://www.blogtalkradio.com/) and [_KCAA Live Stream_](http://live.kcaastreaming.com/).

**Comment by kekukui** [comment]
excellent ... merci beaucoup
