### ISSUE TITLE
sometimes stop button is greyed out - and other functions still work. So I cannot stop a video but I can fast forward, rewind and use other functions. Just stop button is greyed out

### ISSUE THREAD

**Issue by bendy101** [regseb/castkodi#124]
### Describe the bug

sometimes stop button is greyed out - and other functions still work. So I cannot stop a video but I can fast forward, rewind and use other functions. Just stop button is greyed out
### To Reproduce

1. 
2. 
3. 

### Environment

- Cast Kodi version:
- Browser version:
- Kodi version:
- Kodi add-on version (if appropriate):

**Comment by regseb** [comment]
Thank you for opening an issue. Please fill in the information requested in the template.
