### ISSUE TITLE
No Port/User/Password settings => no Connection

### ISSUE THREAD

**Issue by andy5macht** [regseb/castkodi#13]
I was using this addon for years now. But since some time i can not cast to kodi because of a connection issue. As i can see there are missing port/user/password settings. So Cast Kodi doesnt know how to connect?
![grafik](https://user-images.githubusercontent.com/33346822/61318988-95529c00-a806-11e9-8a92-bf580f50b599.png)

**Comment by PeterPedro** [comment]
Yeah, it works in my laptop but not in my desktop, I get the same message from the picture. It's the same kodi box and same settings, no firewall and I can connect with other software.

**Comment by regseb** [comment]
@andy5macht Version 4 of Cast Kodi connects to Kodi with the WebSocket JSON-RPC protocol. _Port_, _Username_ and _Password_ are no longer required. Have you activated _Allow remote control from applications on this system_ and _Allow remote control from applications on other systems_? These parameters can be found in Kodi: _Settings_ / _Services_ / _Control_ / _Application control_ (or in German: _Einstellungen_ / _Dienste_ / _Steuerung_ / _Anwendungskontrolle_ ; _Fernsteuerung durch Anwendungen dieses Rechners erlauben_ and _Fernsteuerung durch Anwendungen andere Rechner erlauben_).
If you open this URL: <http://192.168.0.166:9090/jsonrpc>, does the page load indefinitely or does the connection fail?

@PeterPedro The URL <http://192.168.0.166:9090/jsonrpc> (by changing the IP address) is accessible (load indefinitely) from your laptop and desktop?

**Comment by andy5macht** [comment]
yes i have both options enabled.
the page load indefinitely. what else can i do?

**Comment by PeterPedro** [comment]
@regseb It's working now, I don't know why it wasn't working before, but it's probably my fault. Thanks.

The only problem I have now is that when it's inside the >> menu on the top right it opens with scrollbars and it's a bit annoying but it's not a big deal anyways.

**Comment by regseb** [comment]
@andy5macht If the page loads indefinitely, it means you have access to Kodi. 🤔 You can also test with this URL: `ws://192.168.0.166:9090/jsonrpc`
Maybe the problem is Kodi's version. What is your version of Kodi, Firefox and Cast Kodi?

**Comment by andy5macht** [comment]
`ws://192.168.0.166:9090/jsonrpc` also does never stop loading...

Kodi version 18.3
Firefox version 68.0.1 (64-Bit)
Cast Kodi version 4.2.0

**Comment by regseb** [comment]
I tested with the same versions as you and I don't have a problem. Cast Kodi uses the URL `ws://192.168.0.0.166:9090/jsonrpc` to connect to Kodi. If you have access to it, I don't understand why Cast Kodi can't connect.

You can do this test:

- Open `moz-extension://4dbeb1a6-add8-4c22-8191-ef12886e496e/options/index.html`
- Displays _Firefox Developer Tools_ (with _F12_)
- Go to the _Console_ tab
- Selects all types: _Errors_, _Warnings_, _Logs_, _Info_, _Debug_, _CSS_, _XHR_ and _Requests_
- Deletes the last digit of the _IP address_
- Rewrite the last digit of the _IP address_
- Wait for the warning "_Since version 4.0.0..._" to be displayed
- Copies here the messages displayed in the _Console_

**Comment by andy5macht** [comment]
This: 
- Open moz-extension://4dbeb1a6-add8-4c22-8191-ef12886e496e/options/index.html
was not possible. Instead I opened extensions/addons => Cast Kodi => Settings.
I did all the other steps to get to the console and get logs but nothing appeared.
Maybe i did something wrong?
I tried 32bit version on same PC: works
I tried differen PC with 64bit Firefox: works
I tried to "clean" Firefox 64bit but still not working.
I get mad.

**Comment by andy5macht** [comment]
Now it works! I have no clue why but it works! (Did not change anything after my last comment!)

**Comment by mmmmmat** [comment]
I'm getting this issue as of a few days ago. 

ws://192.168.1.63:9090/jsonrpc loads indefinitely

http://192.168.1.63:8181/jsonrpc loads a json file  "description | "JSON-RPC API of XBMC"" (I'm not sure why my Kodi instance is on a non-standard port but there was a reason and I've been using this extension for a few years with no issue)

Other 'send to Kodi' extensions work for YouTube videos (but don't have remote control which is why I like this one). 

Chorus loads on http://192.168.1.63:8181/ and works fine.

 moz-extension://4dbeb1a6-add8-4c22-8191-ef12886e496e/options/index.html doesn't open.

Firefox 68.0.1 (64-bit) on Debian linux (testing). All extensions fully up to date at time of posting.

**Comment by regseb** [comment]
@andy5macht It's good that it works for you.

@mmmmmat Can you go to the URL `moz-extension://4dbeb1a6-add8-4c22-8191-ef12886e496e/options/index.html`, but by changing `4dbe...496e` to the _Internal UUID_ of Cast Kodi that is displayed on page `about:debugging#addons` ? And follow the instructions in my [previous message](https://github.com/regseb/castkodi/issues/13#issuecomment-515753515).

**Comment by sebastienaubry** [comment]
Hello,
I have the same bug here and followed these instructions. My Kodi server is at 192.168.1.36. I get:
```
GET http://192.168.1.3:9090/jsonrpc
GET http://192.168.1.36:9090/jsonrpc
Firefox can’t establish a connection to the server at ws://192.168.1.3:9090/jsonrpc. (jsonrpc.js:137:27)
Firefox can’t establish a connection to the server at ws://192.168.1.36:9090/jsonrpc.
```

**Comment by mmmmmat** [comment]
Thanks Sébastien, I'll try that. I get the same output as @sebastienaubry 

```
GET http://192.168.1.63:9090/jsonrpc
Firefox can’t establish a connection to the server at ws://192.168.1.63:9090/jsonrpc.
```

**Comment by regseb** [comment]
@mmmmmat Can you test URL <http://192.168.1.63:9090/jsonrpc>?
@sebastienaubry Same with <http://192.168.1.36:9090/jsonrpc>?

**Comment by sebastienaubry** [comment]
For me, it does not work and Firefox loads indefinitely. 
It must not be related to the client, since I get the same behaviour with Firefox for Windows and for Linux.

**Comment by sebastienaubry** [comment]
For me it works on port 8080 with: http://192.168.1.36:8080/jsonrpc:
```
description | "JSON-RPC API of XBMC"
id | "http://xbmc.org/jsonrpc/ServiceDescription.json"
version | "10.3.0"

```

**Comment by regseb** [comment]
It is normal that the page loads indefinitely because the extension connects to Kodi and waits for events. If you access <http://192.168.1.36:9090/jsonrpc>, the extension should also access it. So I don't understand why the extension doesn't work. 😕

**Comment by PeterPedro** [comment]
Unfortunately the issue returned, so it looks like some random behavior either from the addon or from kodi, for me this is the port that works... http://192.168.1.50:8080/jsonrpc it returns this:

`

description | "JSON-RPC API of XBMC"
-- | --
id | "http://xbmc.org/jsonrpc/ServiceDescription.json"
methods | {…}
notifications | {…}
types | {…}
version | "10.1.2"

`

**Comment by mikeperalta1** [comment]
I believe I have a similar problem. In 2 other Kodi-related extensions, I can simply use the hostname "kodi.home" and sometimes fill out the port "8080" (depending on the extension). But with CastKodi, entering any of many combinations of the hostname, raw IP, port/noport, http/https/nothing, doesn't ever seem to connect or work.

**Comment by Wolvverine** [comment]
The option to set port, user and password should be available.These are configurable parameters in kodi.
Not everyone's kodi works on 8080 and without a password user.

**Comment by Wolvverine** [comment]
@regseb 
![image](https://user-images.githubusercontent.com/5873929/202222764-bcf8ac52-dd8f-4250-8807-7f70a2fb3178.png)
![image](https://user-images.githubusercontent.com/5873929/202223218-502841b9-6b62-4d99-8dc4-68d2cadab665.png)

**Comment by Wolvverine** [comment]
》"Go to http://192.168.1.16:18080 with your browser to check that you have access to Kodi (maybe Kodi and your browser aren't on the same local network)."

Above you just have a screenshot of the web interface ;)

**Comment by regseb** [comment]
What value do you have in _Settings_ / _Web Interface_ / _Advanced options_: _Websockets port_ and _Websockets host_ ?

**Comment by Wolvverine** [comment]
ws://192.168.1.16:9090/jsonrpc

Actually is ok

**Comment by regseb** [comment]
@Wolvverine It should work with only the IP address `192.168.1.16` (because you use the default port).
