### ISSUE TITLE
Support Google podcasts

### ISSUE THREAD

**Issue by arigit** [regseb/castkodi#139]
### Describe the problem

Google podcasts are not currently supported

### Describe the solution you'd like

Add support for google podcasts; example url:

https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuY2JjLmNhL3BvZGNhc3RpbmcvaW5jbHVkZXMvY29tZWJ5Y2hhbmNlLnhtbA

### Environment

- Cast Kodi version 7.9.0
- Browser version Firefox 126.0
- Kodi version 20.5
- Kodi add-on version (if appropriate) N/A

**Comment by regseb** [comment]
> After June 23, 2024, Google Podcasts will no longer be available. Start listening on YouTube Music as an alternative. [Learn more](https://support.google.com/youtubemusic/answer/14151168)

Google Podcasts will soon close. It will be replaced by [YouTube Music](https://music.youtube.com/), which is already supported by Cast Kodi (you need the [YouTube](https://kodi.tv/addons/omega/plugin.video.youtube/) addon in Kodi).
