### ISSUE TITLE
Feature request: Add extension shortcut to show remote control

### ISSUE THREAD

**Issue by xyrolaith** [regseb/castkodi#14]
It would be nice having a configurable extensions shortcut for showing the remote control popup.
Alt+K or Ctrl+Alt+K both seem to be unused and would make a good default hotkey.

see https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

**Comment by regseb** [comment]
@xyrolaith In the new version _4.3.0_, you can open the popup with the keyboard shortcut **`Alt+K`**.

**Comment by xyrolaith** [comment]
Thank you for the fast implementation. Already installed and works perfectly.
