### ISSUE TITLE
login mdp en boucle

### ISSUE THREAD

**Issue by clotaireFrance** [regseb/castkodi#148]
### Describe the bug

a la moindre utilisation du plugin, demande login et mdp de l'interface web, en boucle ( n'accepte pas les credentials saisis bien qu'exacts).

librelec 12.0.1 sur raspberry pi  RPi2.arm

chrome Version 131.0.6778.69 (Build officiel) (64 bits)

plugin utilisable. mais pénible cette fenetre de saisie

(" se connecter" " votre connexion a ce site n'est pas privée"  login  / Mdp)

**Comment by regseb** [comment]
Je n'arrive pas reproduire ton problème. Est-ce que tu pourrais donner plus de détails ? Une capture d'écran, ta configuration du _Serveur Web_ (_Paramètres_ / _Services_ / _Contrôle_) dans Kodi.

**Comment by clotaireFrance** [comment]
![image000000 jpg](https://github.com/user-attachments/assets/aa6cf768-b35e-464c-b712-cb94e5a99e1c)
![Capture d’écran du 2024-11-19 20-52-42](https://github.com/user-attachments/assets/24c1390f-7ead-4bef-a9a8-8dd292cccb78)
Voici les captures.

Merci pour ton aide.

**Comment by regseb** [comment]
J'ai réussi à reproduire le même problème qui est seulement dans Chrome 131 et quand l'authentification est activée dans Kodi. J'ai normalement corrigé le bogue, la nouvelle version Cast Kodi est en attente de validation dans le Chrome Web Store.

En attendant la publication de Cast Kodi, tu peux désactiver le _contrôle à distance via HTTP_ dans Kodi. L'extension fonctionnera correctement, mais tu n'auras plus la [Web interface](http://192.168.0.15:8080).

**Comment by clotaireFrance** [comment]
Merci pour ces infos.  j'ai désactivé login mot de passe de l'interface web, ça facilite le tout

**Comment by regseb** [comment]
La version _7.12.1_ de Cast Kodi a été publié. Si tu réactives l’authentification dans Kodi, est-ce que ton problème est résolu ?

**Comment by clotaireFrance** [comment]
c'est fonctionnel. 
Merci bcp.
