### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by hockeymikey** [regseb/castkodi#20]
Allow the user to configure multiple connections and to be able to cast to any of them. Maybe add a drop down in the button menu to allow which one to be selected and on the context menu just add another sub menu where it lists all the connections.

**Comment by regseb** [comment]
@hockeymikey Since version 4.8.0 (requiring Firefox 70+), you can configure multiple connections; and select the connection from the context menu and remote control.

**Comment by hockeymikey** [comment]
@regseb That makes sense, I'm back on 1.4.1 since I'm running Waterfox. How about adding support for it?

**Comment by regseb** [comment]
If you are using version 1.4.1, your version of Waterfox must be based on Firefox 57. The current version of Firefox is 71, it would be complex to make Cast Kodi compatible with this old version.

I only support the latest version because it would take me too long to test on different versions.

**Comment by hockeymikey** [comment]
@regseb Yes, but Waterfox has support for webextensions. Should be fairly straight forward to get working, isn't anything conceivablely difficult or weird that needs to be ported over. Waterfox is a better browser anyways than current Firefox.

**Comment by regseb** [comment]
Sorry I don't have time to support Waterfox.

Maybe in June 2020, Waterfox will be based on Firefox ESR 78 so you can use a newer version of the extension.

**Comment by hockeymikey** [comment]
@regseb No, I won't be using that trash version of Waterfox because all new FF versions are junk without legacy addon support. I'll do it myself then since you're too lazy to even attempt it and even give a half-assed college try.

**Comment by regseb** [comment]
Good luck and have fun! ❤️

**Comment by hockeymikey** [comment]
You're the worst.
