### ISSUE TITLE
Option to pass user-agent to Kodi

### ISSUE THREAD

**Issue by lukoerfer** [regseb/castkodi#22]
Hi, great work on the addon!
I would like to propose a new feature. If you are interested, I would even work on it by myself and create a pull-request, as long as you do not prefer working on the addon on your own.

I encountered a problem when casting video URLs of some domains to Kodi, because the servers would refuse the connection when the user-agent of the request does not belong to a common browser (this can be easily checked with `curl`). Until know, I could not find an option in Kodi to change the user-agent for every request, but Kodi allows passing a custom user-agent by adding options to the URL string as described [here](https://kodi.wiki/view/HTTP). 

The technical implementation of patching the link would be rather simple, regarding the configuration interface two options came to my mind:

1. Add a simple switch (check-box) that adds the current browser user-agent to every link casted to Kodi when enabled.
2. Add a text field to pass any HTTP options to Kodi. The contents of the text field would simply be added to every link casted to Kodi. This way, every HTTP option supported by Kodi could be used, but with a little bit more effort and expert knowledge.

Keep up the great work and happy holidays!

**Comment by regseb** [comment]
Thank you for your detailed proposal.

If the videos can't be played with Kodi's _user-agent_: don't use an option, but overload by default the _user-agent_ (using the browser's one). Do you have an example of a URL that doesn't work?

**Comment by lukoerfer** [comment]
I encountered problems when casting video URLs from [Vidoza](https://vidoza.co/). I created an example using the free movie [*Big Buck Bunny*](https://vidoza.co/v1jwgv39nfyi). If you navigate to the URL of the [actual video](https://str17.vidoza.net/x4lfjay3hrz7vjumxabf2tqq6bnmjr75kwwkzpy27q25h7luml5foovlfwlq/v.mp4) (`src` of `video` element) when accessing the video from the [embedded URL](https://vidoza.co/embed-v1jwgv39nfyi.html), the video can be viewed in the browser. The video can then be casted to Kodi using the addon, but the playback stops instantly. After adding the user-agent option to the URL as you can see below, the resulting URL cannot be resolved by the browser, but it can be casted to Kodi and the video playback works:

https://str17.vidoza.net/x4lfjay3hrz7vjumxabf2tqq6bnmjr75kwwkzpy27q25h7luml5p2bvlfwkq/v.mp4|user-agent=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64;%20rv:71.0)%20Gecko/20100101%20Firefox/71.0

When using the video URL directly and not via the embedded link, it works without passing the user-agent. I don't know why Vidoza works that way, but there may be other servers handling requests in a similar way.

**Comment by regseb** [comment]
I've tested with both URLs and they work.

- [regular](https://vidoza.org/v1jwgv39nfyi): Kodi plays the file [https://str17.vidoza.net/x4lfjay3hr[...]zfo4tb246q/v.mp4](https://str17.vidoza.net/x4lfjay3hrz7vjumxabf2tqq6bnmjr75kwwkzpy27q25htfyzmzfo4tb246q/v.mp4);
- [embed](https://vidoza.org/embed-v1jwgv39nfyi.html): Kodi plays the file https://str17.vidoza.net/x4lfjay3hr[...]zc64tb247q/v.mp4.

Maybe your Kodi's _user-agent_ is different. I use _OSMC running Kodi 18.5_ (_Settings_ / _System information_ / _Summary_) which sends the user-agent `Kodi/18.5 (X11; Linux armv7l) Linux/2019.11-1 HW_RaspberryPi/1.0 App_Bitness/32 Version/18.5`. Can you check with `curl` that this user-agent works?

What is your _user-agent_? You can get it by sending this URL to Kodi: http://ptsv2.com/t/djq0x-1578138764/post. And you can see the requests sent by Kodi at this URL: http://ptsv2.com/t/djq0x-1578138764.
