### ISSUE TITLE
ResolveURL or URLResolve feature ??

### ISSUE THREAD

**Issue by DjDiabolik** [regseb/castkodi#25]
I'm right now tryed to cast this to my kodi setup:
https://vidlox.me/30fxi9o50b3v

The video links apparently it's correctly added to playlist but it's fail to reproduce.... it's appears a blue spin for a moment and nothings appends.

It's need problably the ResolveURL or the URLREsolver for obtain the main links for stream it correctly... you can add this feature ?

*EDIT*
Apparently there's a direct mirror to this files:
https://c30.vidlox.me/hls/oudvhyeh5btk2yixv6jowv3xjcuqzkaso7elzrhtqqjwsvj24kwmramrazka/index-v1-a1.m3u8

Or add a way to add a direct mirrors.... somethings to send a direct mirrors to playlist.

**Comment by regseb** [comment]
Support for _Vidlox_ has been added in Cast Kodi _4.17.0_ (requires Firefox _75_). _ResolveURL_ and _URLresolver_ are not required, Cast Kodi extracts the video URL and sends it directly to Kodi.
