### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by mcrypt** [regseb/castkodi#27]
After latest update its not working.. 
castkodi version 4.17.0
firefox version 75.0
error message "Failed to execute method"

**Comment by Cygn** [comment]
Hey, I see the same thing. How did you fixed it ?

**Comment by regseb** [comment]
When you open the popup and the Kodi audio player is active, this error will display: _Failed to execute method_. I fixed this problem with version _4.17.1_. For information, the Cast Kodi remote only controls video player.
