### ISSUE TITLE
Uptostream

### ISSUE THREAD

**Issue by Wolsey20** [regseb/castkodi#28]
Hello,

Could you add uptostream.com support

Thank you

**Comment by regseb** [comment]
I'll see if it's possible to extract video from the pages.

**Comment by Wolsey20** [comment]
it works with this extension, but it is less complete than castkodi

https://addons.mozilla.org/fr/firefox/addon/kodi-control/

**Comment by regseb** [comment]
I'm closing the issue because Uptobox is no longer available. https://uptobox.info/
