### ISSUE TITLE
Feature: Send Text

### ISSUE THREAD

**Issue by quthla** [regseb/castkodi#30]
It'd be great if the addon supported sending text to Kodi when Kodi is showing a text input. This is useful when searching for content in addons for example.

The official web interface does support it.

https://kodi.wiki/view/JSON-RPC_API/v10#Input.OnInputRequested
https://kodi.wiki/view/JSON-RPC_API/v10#Input.SendText

**Comment by regseb** [comment]
It's a good idea. I'll see how to add it to the remote.

**Comment by regseb** [comment]
@quthla With version _5.2.0_ you can send text to Kodi from the remote control.

**Comment by quthla** [comment]
Thanks, I see the option.

It seems though that you didn't hook the event. You could automatically display the send text window when Kodi requests input.

https://kodi.wiki/view/JSON-RPC_API/v10#Input.OnInputRequested

**Comment by regseb** [comment]
@quthla With version _5.6.0_, when input is requested in Kodi: the send text window opens automatically.
