### ISSUE TITLE
PVR can't be stopped

### ISSUE THREAD

**Issue by quthla** [regseb/castkodi#33]
The stop button is disabled when Kodi is playing a PVR live stream.

https://github.com/regseb/castkodi/blob/master/src/popup/script.js#L424

This is what's causing it. Position is meant to be the position in the playlist. Not sure what you're trying to achieve by comparing it to -1 but at least for PVR, it's breaking stuff.

**Comment by regseb** [comment]
The problem has been fixed in version _7.9.0_ of Cast Kodi (which requires Chrome 124+ or Firefox 125+).
