### ISSUE TITLE
Anyone what addon I need to cast HTML5 videos to kodi from Firefox?

### ISSUE THREAD

**Issue by Mech0z** [regseb/castkodi#40]
I have installed https://addons.mozilla.org/da/firefox/addon/castkodi/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

But when I cast the video link from HTML5 videos on websites nothing happens,

Twitch works fine so there is a connection, but it just cant handle

**Comment by regseb** [comment]
@Mech0z If the HTML document of the page contains a `<video>` or `<audio>` tag, it's sent to Kodi and you don't need to have an add-on. If the `<video>` or `<audio>` is added by JavaScript, native detection doesn't work.

Do you have an example of a page that doesn't work?

**Comment by BadIDMan** [comment]
What about live sport on http://livetv.sx ?
Is it possible to cast them to Kodi?

**Comment by regseb** [comment]
@eusru Do you have an example that used to work and no longer does?

For Miracast and AirPlay, I think it works differently: it's the phone that streams the video to the TV. With Cast Kodi, only the link of the video is sent and it's Kodi that plays it. After sending the video, you can close the browser and turn off the PC.

**Comment by eusru** [comment]
> @eusru Do you have an example that used to work and no longer does?
> 
> For Miracast and AirPlay, I think it works differently: it's the phone that streams the video to the TV. With Cast Kodi, only the link of the video is sent and it's Kodi that plays it. After sending the video, you can close the browser and turn off the PC.

yeah I have
I  use the Supported Websites cast to kodi successfully, but if my website is not in your supported list, it cannot work most of the time.

for Miracast and airplay.I just wanna use Cast to koki like phone just for easy!.It seems sent a url to kodi to play this url by Plugins like YouTube Plugin on Kodi.

**Comment by regseb** [comment]
> yeah I have

I will try to support websites in Cast Kodi.

**Comment by eusru** [comment]
> > yeah I have
> 
> I will try to support websites in Cast Kodi.

You're awesome.Thanks for this plugin
