### ISSUE TITLE
Add button to open web interface

### ISSUE THREAD

**Issue by FloEdelmann** [regseb/castkodi#42]
If the Kodi server has its web interface enabled, it'd be nice to have a button in the popup that lets users open this web interface in a new tab. This can e.g. be useful to queue videos/music that is stored on the Kodi server and not streamed from a website.

**Comment by regseb** [comment]
The button (a globe at the bottom of the popup) has been added in version _5.7.0_ of Cast Kodi (requires Firefox _84_). The button is displayed if the web interface is enabled with port `8080`.

**Comment by FloEdelmann** [comment]
Nice, thank you :)
