### ISSUE TITLE
Color codes in movie titles should either be stripped off or interpreted

### ISSUE THREAD

**Issue by jose1711** [regseb/castkodi#47]
Currently, if movie's title contains color tags, e. g. `[COLOR blue]Movie name[/COLOR]` they're shown as-is making the title display a bit awkward. Not sure if they can be turned into HTML easily but removing them entirely would probably be an alternative.

**Comment by regseb** [comment]
@jose1711 Thanks for your feedback.

With new version _5.8.0_ (requires Firefox _84_+), tags for formatting labels are removed. With the solution to convert them to _HTML_, it could have complications (black text on black, or in bold when bold is used to indicate the current item).
