### ISSUE TITLE
YouTube playlist

### ISSUE THREAD

**Issue by dean-github** [regseb/castkodi#5]
Hi,
When you send the link of a video on the Playlist, an error on kodi would say "Playback failed".
If you set the mode to "Cast video only" it would work for single video.
Please help fix it.
Thanks

**Comment by regseb** [comment]
@dean-github I tested sending a playlist and it works. Do you have an example of a problematic playlist?

**Comment by dean-github** [comment]
@regseb Here's an example I tried just now and it failed with "Playback failed": http://prntscr.com/n260cm.
I am using OSMC on RPI 3, not sure if this has any difference with KODI you tried.
Thanks

**Comment by regseb** [comment]
@dean-github I reproduced the error with the [playlist](https://www.youtube.com/watch?v=8xg3vE8Ie_E&list=PL1CbxROoA2JiVzg9zu_AkVHZR9S8mHhzh):

> Playback failed
> One or more items failed to play. Check the log for more informations about this message.

The problem comes from Kodi's YouTube plugin:

```
12:04:55.860 T:1224729344  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.0) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'playlist_id': 'PL1CbxROoA2JiVzg9zu_AkVHZR9S8mHhzh'}
12:05:09.281 T:1224729344   ERROR: /home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
12:05:14.745 T:1925894736   ERROR: Previous line repeats 2 times.
12:05:14.746 T:1925894736   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?playlist_id=PL1CbxROoA2JiVzg9zu_AkVHZR9S8mHhzh]
```

As indicated in this [issue](https://github.com/jdf76/plugin.video.youtube/issues/198), I have enabled _Settings_ / _Advanced_ / _Force SSL certificate verification_ of the Kodi's YouTube plugin and the playlist launches correctly.

**Comment by dean-github** [comment]
I see, thank you very much for your time and support.

**Comment by dean-github** [comment]
@regseb You're right, today I tested this again, I disabled "Force SSL cert. verification" option and it works.
Thanks for your time.
Cheers
