### ISSUE TITLE
Facebook video

### ISSUE THREAD

**Issue by dean-github** [regseb/castkodi#6]
Hello,
Today I tried to test this addon with FB video and it always says " link isn't a FB video".
Could you please have test and fix it?
Thanks

**Comment by regseb** [comment]
The extension could not retrieve the URL of the video because Facebook changed the structure of the pages. Version 3.3.2 fixes this problem.

@dean-github If you still have a problem, can you provide the video link.

**Comment by dean-github** [comment]
@regseb It works, thanks for your update.

**Comment by igitur** [comment]
Before I open a new issue, let me ask first. Did Facebook change their pages again?

https://www.facebook.com/1764992706915926/videos/223285912075605/

Can't play this on Kodi.
