### ISSUE TITLE
Integrate "Mediatheken" from MediathekView

### ISSUE THREAD

**Issue by ElsaBergstrom** [regseb/castkodi#61]
Your plugin is really cool!!
With Kodi I use the plugin "MediathekView Kodi Addon". This plugin makes films available from many German tv channels (i.e. from many German "Mediatheken").
The code for the MediathekView server that searches the "Mediatheken" and finds the URLs of the films is here: https://github.com/mediathekview/MServer.
In the code one could probably look up how to find the film URLs from a lot of additional German "Mediatheken" and integrate them in your plugin. Could you do this? That would be great!

**Comment by regseb** [comment]
The extension supports _Arte_ and _ZDF_ websites. Since version _5.16.0_, there is also _ARD Mediathek_.

**Comment by ElsaBergstrom** [comment]
Thanks a lot!
Unluckily I cannot get ARD Mediathek working in version 6.1.1 of Cast Kodi.
For instance this link:
https://www.ardmediathek.de/video/kranitz-bei-trennung-geld-zurueck/folge-4-manni-und-sandy-barmbek-statt-bahamas-s01-e04/ndr-fernsehen/Y3JpZDovL25kci5kZS8wYzkxNjlhYi04MTU1LTQzNmMtOTQyMC0wZjQ2MDVkYjFmOTI/

Video DownloadHelper finds:
https://adaptive-ndr.akamaized.net/i/ndr/2021/1009/TV-20211009-1543-3300.,hd,hq,ln,mn,ao,.mp4.csmil/index-f1-v1-a1.m3u8

When I search
https://mediathekviewweb.de/
for
kranitz 4
I find many URLs, for instance
https://mediandr-a.akamaihd.net/progressive/2021/1009/TV-20211009-1543-3300.hd.mp4

The links from Video DownloadHelper and MediathekVieWweb can be sent to kodi to play the film.

Cast Kodi finds:
plugin://plugin.video.ardmediathek_de/?client=ard&mode=libArdPlay&id=Y3JpZDovL25kci5kZS8wYzkxNjlhYi04MTU1LTQzNmMtOTQyMC0wZjQ2MDVkYjFmOTI

This does not work.
