### ISSUE TITLE
Support for plugin.video.tubed (YouTube addon)

### ISSUE THREAD

**Issue by wagnerch** [regseb/castkodi#62]
It appears the existing YouTube add-on for Kodi is going to eventually phased out and replaced by Tubed (https://github.com/anxdpanic/plugin.video.tubed).

Can support be added for this plugin w/ some sort of configuration option or auto-discovery (https://kodi.wiki/view/JSON-RPC_API/v12#Addons.GetAddons) to switch between plugins to cast to?

**Comment by regseb** [comment]
It should be possible to support two plugins. But Tubed doesn't seem to have URL `plugin://plugin.video.youtube/play/?video_id=$VIDEOID` (like [YouTube](https://kodi.wiki/view/Add-on:YouTube)). So Cast Kodi can't send a video ID to Tubed.

**Comment by wagnerch** [comment]
I think it does, it appears to be:
plugin://plugin.video.tubed/play/?video_id=$VIDEOID

I haven't tested it, but there is a xbmc.python.script extension point with a "router" decorator that appears to parse the script arguments, which I think that should work?  I think that is similar to how the Netflix plugin works.

https://github.com/anxdpanic/plugin.video.tubed/blob/0d38e420582dbef0d44c398f8804715622f82b63/resources/lib/src/script.py#L135

I do not have the add-on installed at the moment, but I could install it -- how would I be able to test if this URL works for a video id?

**Comment by regseb** [comment]
> plugin://plugin.video.tubed/play/?video_id=$VIDEOID

I tested this URL, but I have the error:

```
2021-09-02 19:08:44.327 T:15219    INFO <general>: JSONRPC Server: New connection added
2021-09-02 19:08:44.376 T:15332    INFO <general>: initializing python engine.
2021-09-02 19:08:44.386 T:15332    INFO <general>: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.tubed/resources/lib/addon.py): script successfully run
2021-09-02 19:08:44.386 T:15185   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tubed/play/?video_id=dQw4w9WgXcQ]
```

**Comment by wagnerch** [comment]
Found this on the forums, not sure if it is right or works:

```
plugin://plugin.video.tubed/?mode=play&video_id=<id>
```

https://forum.kodi.tv/showthread.php?tid=358806&pid=3024964#pid3024964

**Comment by regseb** [comment]
The new version _6.1.0_ of Cast Kodi supports the Tubed addon. The videos are sent to the addon installed in Kodi (_plugin.video.youtube_ or _plugin.video.tubed_). If both addons are installed: the videos are sent to _plugin.video.youtube_.

@wagnerch Thanks for all the information given.
