### ISSUE TITLE
Cast Kodi is working only partial

### ISSUE THREAD

**Issue by Cris--** [regseb/castkodi#64]
Hi,

i have the problem that only some functions are working.
If i send a url stream like SomaFM Space Station from my phone to my Kodi on a RPi4 via Yatse Kodi plays the stream.

Now if i look on my Laptop with "Cast Kodi" i see this:

![ScreenShot - Cast Kodi](https://user-images.githubusercontent.com/7994691/130019728-5b7a5aa6-a8c6-4ef0-a16e-17915a80d156.png)

So i didn't see whats playing now and some remote controls not active.
With the "Echo for Kodi" addon i see this:

![ScreenShot - Echo for Kodi](https://user-images.githubusercontent.com/7994691/130019866-9f5ac0ea-a686-41a5-ae36-e9f07f18bb51.png)

All functions are working and i see what's playing now.

What i have:
RPi4 with LibreElec 9.2.8 / Kodi 18.9.0 leia
Windows 10 Pro 21H2 / Firefox 91.0.1 / Cast Kodi 5.15.0

What i did to fix this:
Start with only Cast Kodi addon active.
Cleared FF cache/cookies
Tried with _192.168.10.4_ or _ws://192.168.10.4:9090/jsonrpc_

**Comment by regseb** [comment]
Cast Kodi manages only the video player. I assume that the _SomaFM Space Station_ URL points to music and Yatse sends it to the Kodi audio player. So there is nothing in the video player.

**Comment by regseb** [comment]
Sorry, but this isn't planned because it would make the code more complex and it also brings disadvantages.
