### ISSUE TITLE
Chrome Web Store Version

### ISSUE THREAD

**Issue by Kariton** [regseb/castkodi#65]
I it planed or possible to relase a version for chromium based browsers?
There is no such great plugin for kodi. I love Cast Kodi.

the only reason to keep Firefox - just to send videos to Kodi and manage playback. :)

**Comment by regseb** [comment]
I published the extension on the [**Chrome Web Store**](https://chrome.google.com/webstore/detail/cast-kodi/gojlijimdlgjlliggedhakpefimkedmb). It's unlisted for a _beta_ period. If you find any problems, you can create an issue.
