### ISSUE TITLE
Why no support for Kodi 18.7?

### ISSUE THREAD

**Issue by DanielVolz** [regseb/castkodi#68]
Hey,

I'm on the newest version of Raspbian 10 buster but unfortunately Kodi 19 is still not released for this Raspbian version.
Previously I used this add-on without problems with 18.7 but unfortunately that support was dropped.

Is it possible to make this add-on backwards compatible with 18.7?

Thanks!

**Comment by regseb** [comment]
I agree that this message isn't true. But it's a simple sentence to explain to users that they might have problems with Kodi 18.
