### ISSUE TITLE
Option to reverse mouse scrolling direction to control volume

### ISSUE THREAD

**Issue by wizetek** [regseb/castkodi#69]
### Describe the problem

Currently, at least on my system, clicking on the Cast Kodi toolbar button in Firefox and then scrolling up and down controls volume where the _up_ motion _decreases_ and the _down_ motion _increases_ it.

### Describe the solution you'd like

It would be great to have a configuration option to reverse the scrolling direction in order to accommodate people to whom the default behavior feels unnatural and counterintuitive.

### Environment

- Cast Kodi version: 6.1.1
- Kodi version: 19.3
- Browser version: 93.0

### Additional context

Thank you for all your time and effort and for the consideration. Cheers.

**Comment by regseb** [comment]
Cast Kodi 7.0.0 (requiring Chrome 109 or Firefox 109) has a new option to control the volume with the wheel. Three choices are possible: _normal_, _reverse_ or _disabled_.

**Comment by wizetek** [comment]
It's working great. Many thanks for implementing this.
