### ISSUE TITLE
How to send Facebook (live) video to Kodi with CastKodi?

### ISSUE THREAD

**Issue by sorin-pop** [regseb/castkodi#7]
Hi regseb,

I would like to play Facebook videos, especially live streams, on my Kodi. So I am trying out your Cast Kodi extension for Firefox, because it explicitly lists facebook as supported:

> videos: direct links (avi, mkv, ...), YouTube, Twitch, Vimeo, Instagram, torrents, magnets and Ace Stream, AlloCiné, Dailymotion, DevTube, Dumpert, Facebook, Flickr, Full30, JeuxVideoCom, PeerTube, Pippa, Rutube, StormoTV, ...

However, I am not quite sure how I can do that, I can't figure it out. When right-clicking on facebook video, I do not get the "Play now to Kodi" context menu. But I do see it when right-clicking on youtube videos. What am I missing? Is there some other way of using this add-on for facebook videos and live streams? (The first ticket was also related to facebook, but unfortunately the user did not specify how exactly he tried playing the fb video)

Thanks in advance for your assistance.

**Comment by sorin-pop** [comment]
In the meantime I managed to make some progress. I was able to make it work by using the "Paste link" icon in the addon, but apparenly only for non-live videos. And I could also see the context menu in a few instances now.

But not for a live video. And after pasting the link and clicking play, I got the same error as the user in the first ticket (that it is not a valid fb link or something similar). Here is for example such a link: https://www.facebook.com/foxcarolinanews/videos/2332364197043199/

Can you please double-check if the addon works with facebook live stream videos? And if yes, how?

I am using the latest version: 3.3.2

**Comment by regseb** [comment]
I tested the video you provided and I can't send it either. There is a problem with live videos (the extension does not find the URL of the video in the page). I'll look into trying to correct this case.

For Facebook, it is not easy to send a video because Facebook overloads the context menu. After _Show video URL_, you can directly send the video link by selected the URL:

![facebook](https://user-images.githubusercontent.com/1262990/57148338-ad9b4900-6dc9-11e9-89c3-3483dd05170c.png)

**Comment by regseb** [comment]
I have published a new version (_3.3.3_) that allows you to send reruns of Facebook Live. But I couldn't fix live. 😞

**Comment by sorin-pop** [comment]
Thank you, no problem :)
