### ISSUE TITLE
sendText dialog fails to open under web-ext run

### ISSUE THREAD

**Issue by pespin** [regseb/castkodi#71]
Now that I have a version of kodi supporting the feature, I was trying to update my PR adding support to send subtitle URLs to it (https://github.com/regseb/castkodi/pull/43).

Since there's still no proper documentation on how to develop/test the addon (https://github.com/regseb/castkodi/issues/35), I manage to find out I can test it using following command under root directory of castkodi.git:

`git clean -fxd && web-ext build -s src/ && web-ext run -t firefox-desktop -s src/ --verbose`

Then, firefox is started with a new profile and the addon loaded in, and I configure it against my kodi instance. Stuff seems to work in general, however, when I press the "Send text" button to open a new dialog to fill in the text, it actually fails and no dialog is open. Instead, I see this in the web console (or web-ext run --verbose output in the terminal):

`[firefox/index.js][debug] Firefox stderr: JavaScript error: moz-extension://fbe06268-ceb3-4286-8737-6019d3bdff6f/popup/script.js, line 443: TypeError: dialog.showModal is not a function`

The same castkodi version (6.2.0) installed from the firefox official addon download site I use in my regular firefox seems to be working fine though, so it seems to be something related to web-ext.

I tried adding the following line before the error to see what's going one:
`console.log("dialog: ", dialog);`

And I get:
`dialog:  <unavailable>`

castkodi version: v6.2.0
firefox --version: Mozilla Firefox 95.0.2

Having this kind of issue when running with web-ext makes it difficult to improve castkodi, since I cannot test the feature I'm adding (which uses similar dialog as sendText like you advised).

**Comment by regseb** [comment]
You need [Node.js and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm). At the root of the project, run the command: `npm install` (to install the _dialog-polyfill_ dependency).

You can then use `npm run start:firefox` to deploy the extension in Firefox.

**Comment by pespin** [comment]
Thanks, using those commands fixed the issue. This should definitely be in some README file as per #35.
