### ISSUE TITLE
Foxy Gestures support

### ISSUE THREAD

**Issue by pyuk** [regseb/castkodi#74]
[Foxy Gestures](https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/) is an addon that allows using mouse gestures to perform certain tasks. According to [this comment](https://github.com/marklieberman/foxygestures/issues/223#issuecomment-364211282) by the developer of Foxy Gestures, if you add a listener using [runtime.onMessageExternal](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessageExternal) ([here](https://github.com/stoically/temporary-containers/commit/02a9da39f62813a0d50c0affa6b2976fd0065527) is how [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) implemented this), it seems to me it should be possible to use gestures to interact with Cast Kodi using [Foxy Gestures user scripts](https://github.com/marklieberman/foxygestures/wiki/User-Scripts) ([here](https://github.com/stoically/temporary-containers/issues/50#issuecomment-364718479) are 3 user scripts Temporary Containers made).

I feel like being able to use gestures over a link to a video to play now to kodi, play next to kodi and queue item to kodi would be amazing. And maybe if it's easy using a gesture to play/pause, go to next and go back 30 seconds as well. Please consider implementing this and creating some user scripts.

**Comment by regseb** [comment]
Sorry, but I will not implement this feature. I don't want to open Cast Kodi to other extensions for security reasons. External code will have access to Kodi.
