### ISSUE TITLE
Feature request: Remote control

### ISSUE THREAD

**Issue by alfieoriginal** [regseb/castkodi#8]
Hi, good work. In addition with the extension window open, I would like to get more keyboard keys to remotely control Kodi. These keys would be: Arrow keys, Enter, "C" context menu, "i" info menu...
It would be great to make this extension Android Firefox compatible aswell.
Thanks.

**Comment by regseb** [comment]
The idea of the remote to navigate in Kodi is good. Kodi's _JSON-RPC API_ seems to handle these commands. I will look to add that.

For the Android version, it is not possible to port the extension because [`contextMenus` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus) doesn't support for Firefox Android ([_Bugzilla 1269062_](https://bugzilla.mozilla.org/show_bug.cgi?id=1269062)).

**Comment by regseb** [comment]
@alfieoriginal I published a version (_4.0.0_) with the new actions in the remote control.

![Remonte control](https://addons.cdn.mozilla.net/user-media/previews/thumbs/220/220867.png)

**Comment by quthla** [comment]
Found this addon today and it's really well done.

What I'm missing is a button and shortcut [1] to toggle fullscreen mode `GUI.SetFullscreen`. Kodi uses the tab key [2] for this.

[1] https://github.com/regseb/castkodi/blob/master/src/popup/script.js#L668
[2] https://kodi.wiki/view/Keyboard_controls

**Comment by quthla** [comment]
I've made the neccessary change myself and also fixed two issues.

1. Using backspace to go back in Kodi made the browser go back in history because you didn't prevent the according key event in onkeydown
2. Key repeat on key hold didn't work because you only mapped the keys in onkeyup and not onkeydown. I removed onkeyup completely.

```
window.onkeydown = function (event) {
    // Ignorer les entrées avec une touche de modification.
    if (event.altKey || event.ctrlKey || event.metaKey || event.shiftKey) {
        return;
    }

    if ("TEXTAREA" === event.target.tagName) {
        if ("Enter" === event.key) {
            send();
            event.preventDefault();
        }
        return;
    }

    switch (event.key) {
        case "p": case "P": send(); break;
        case "n": case "N": insert(); break;
        case "q": case "Q": add(); break;
        case "v": case "V": paste(); break;
        case "PageUp": previous(); break;
        case "r": case "R": rewind(); break;
        case "x": case "X": stop(); break;
        case " ": playPause(); break;
        case "f": case "F": forward(); break;
        case "PageDown": next(); break;
        case "F8": setMute(); break;
        case "-": setVolume(-5); break;
        case "+": case "=": setVolume(5); break;
        case "c": case "C": contextMenu(); break;
        case "ArrowUp": up(); break;
        case "i": case "I": info(); break;
        case "ArrowLeft": left(); break;
        case "Enter": select(); break;
        case "ArrowRight": right(); break;
        case "Backspace": back(); break;
        case "ArrowDown": down(); break;
        case "m": case "M": showOSD(); break;
        case "Tab": toggleFullscreen(); break;
        // Appliquer le traitement par défaut pour les autres entrées.
        default: return;
    }
    event.preventDefault();
};

const toggleFullscreen = function () {
    jsonrpc.toggleFullscreen().catch(notify);
};

    /**
     * Toggle fullscreen mode
     *
     * @function toggleFullscreen
     * @returns {Promise} La réponse de Kodi.
     */
    toggleFullscreen() {
        return this.request("Gui.SetFullscreen", { "fullscreen": "toggle" });
    }
```

**Comment by regseb** [comment]
@quthla Thank you for your suggestions, feedback and code. I have integrated everything in version _4.8.0_. I have only set the volume steps to _1_ now that the key repeat works.
