### ISSUE TITLE
Feature request: paste and send button

### ISSUE THREAD

**Issue by jayshomebrew** [regseb/castkodi#85]
Thanks for such a great add-on. This is just a feature request to add a button to the paste screen, that pastes the clipboard contents, and hits <enter> or send.  
I already know about the shortcut key 'V' for getting to the paste screen, but on that blank text panel, I'm requesting a 'paste and send' button.  Please correct me if this already exists.

**Comment by regseb** [comment]
- For a clickable link in the browser: right-click on the link, then _Cast to Kodi_.
- For a link that is not clickable in the browser: select (highlight) the link, right-click on the link, then _Cast to Kodi_.
- For a link outside the browser:
  - copy the link to the clipboard;
  - in the browser:
    - open the popup of the extension (or with the keyboard shortcut: `Alt`+`K`);
    - click on _Paste link..._ (or `V`);
    - paste the link (or `Ctrl`+`V`);
    - click on _Play now to Kodi_ (or `Enter`).

I agree that there are many steps. But a _Paste and play now_ button would have a behavior too close to the _Paste link..._ button. It might confuse the user. And we would also have to add the _Paste and play next_ and _Paste and queue item_ buttons. I prefer not to add this button.

I'll look to pre-filling the field with the clipboard content. That will remove one step.

**Comment by regseb** [comment]
@jayshomebrew In the latest version 6.9.0 of Cast Kodi, there is a new option to pre-fill the field with the clipboard content.
