### ISSUE TITLE
How to login using username and password

### ISSUE THREAD

**Issue by baronleonardo** [regseb/castkodi#90]
### Describe the problem

My kodi configuration need the username and password for login.

### Describe the solution you'd like

I want in the preference to input the username and password

### Environment

- Cast Kodi version 6.10.0
- Firefox 107.0.1
- Kodi version 19.4:
- Kodi add-on version YouTube 6.8.18+matrix.1

**Comment by regseb** [comment]
Cast Kodi connects to Kodi with a WebSocket. For this type of connection, there is no username and password. You only need to enter the IP address of Kodi.
