### ISSUE TITLE
Scrolling through the video playlist unexpectedly changes the Kodi volume

### ISSUE THREAD

**Issue by nickrbogdanov** [regseb/castkodi#91]
Sometimes I have a bunch of YouTube videos queued and I want to use the mouse wheel to scroll through the list in the bottom pane of the Cast Kodi window.  Unfortunately, due to https://github.com/regseb/castkodi/pull/23/commits/fc7cb2b8b479e8176e98ca7854d4f28f0156442f , mouse wheel actions anywhere in the window will change the volume.  This is unexpected behavior.

Also, many Kodi users (including myself) *never* want to change the Kodi volume.  It would be useful to me if Cast Kodi could be configured to never touch the Kodi volume level, possibly as part of https://github.com/regseb/castkodi/issues/69

**Comment by regseb** [comment]
Cast Kodi 7.0.0 (requiring Chrome 109 or Firefox 109) has a new option to control the volume with the wheel. Three choices are possible: _normal_, _reverse_ or _disabled_.
