### ISSUE TITLE
Invalid configuration for Kodi Server

### ISSUE THREAD

**Issue by ph818** [regseb/castkodi#96]
I have followed the instructions and configured the extension to look for the following two servers:

* http://192.168.1.157:8080
* http://192.168.1.168:8080

however I get the yellow "!" and a message saying that it either isn't the correct address, or I have not allowed Kodi's remote control. I have gone into the web interface and allowed both remote control from applications on this system and from applications on other systems.

What else could be going on and how could I find out?
Thanks!

**Comment by regseb** [comment]
The placeholder of the field has: `192.168.0.1`. And in the tooltip, you have this description: _IP address or full address (for example : 192.168.0.1, ws://192.168.0.1:9090/jsonrpc, etc.)_

You have to put only the IP address in the field: `192.168.1.157` or `192.168.1.168`

---

If it doesn't work:

- Go to <http://192.168.1.157:8080/#settings/web> (and <http://192.168.1.168:8080/#settings/web>) with your browser.
- What value do you have in _Settings_ / _Web Interface_ / _Advanced options_: _Websockets port_ and _Websockets host_?
